// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DbPZPN))]
    [Migration("20260420141737_calosc")]
    partial class calosc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Klub", b =>
                {
                    b.Property<int>("KlubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlubId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("rokZalozenia")
                        .HasColumnType("TINYINT");

                    b.HasKey("KlubId");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            KlubId = 1,
                            Nazwa = "Legia Warszawa",
                            rokZalozenia = (byte)227
                        },
                        new
                        {
                            KlubId = 2,
                            Nazwa = "Lech Poznań",
                            rokZalozenia = (byte)153
                        });
                });

            modelBuilder.Entity("Domain.Statystyka", b =>
                {
                    b.Property<int>("StatystykaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatystykaId"));

                    b.Property<int>("ZawodnikId")
                        .HasColumnType("int");

                    b.Property<byte>("rozegraneMecze")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("zdobyteGole")
                        .HasColumnType("TINYINT");

                    b.HasKey("StatystykaId");

                    b.HasIndex("ZawodnikId")
                        .IsUnique();

                    b.ToTable("Statystyki");

                    b.HasData(
                        new
                        {
                            StatystykaId = 1,
                            ZawodnikId = 1,
                            rozegraneMecze = (byte)120,
                            zdobyteGole = (byte)85
                        },
                        new
                        {
                            StatystykaId = 2,
                            ZawodnikId = 2,
                            rozegraneMecze = (byte)45,
                            zdobyteGole = (byte)5
                        });
                });

            modelBuilder.Entity("Domain.Zawodnik", b =>
                {
                    b.Property<int>("ZawodnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZawodnikId"));

                    b.Property<int?>("KlubId")
                        .HasColumnType("int");

                    b.Property<bool>("czyKontuzja")
                        .HasColumnType("bit");

                    b.Property<string>("imie")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("kondycja")
                        .HasColumnType("NUMERIC(2,1)");

                    b.Property<byte>("nrKoszulki")
                        .HasColumnType("TINYINT");

                    b.HasKey("ZawodnikId");

                    b.HasIndex("KlubId");

                    b.ToTable("Zawodnicy");

                    b.HasData(
                        new
                        {
                            ZawodnikId = 1,
                            KlubId = 1,
                            czyKontuzja = false,
                            imie = "Robert",
                            kondycja = 9.5m,
                            nrKoszulki = (byte)9
                        },
                        new
                        {
                            ZawodnikId = 2,
                            KlubId = 2,
                            czyKontuzja = true,
                            imie = "Kamil",
                            kondycja = 7m,
                            nrKoszulki = (byte)15
                        },
                        new
                        {
                            ZawodnikId = 3,
                            czyKontuzja = false,
                            imie = "Wojciech",
                            kondycja = 8m,
                            nrKoszulki = (byte)1
                        });
                });

            modelBuilder.Entity("Domain.Statystyka", b =>
                {
                    b.HasOne("Domain.Zawodnik", "Zawodnik")
                        .WithOne("Statystyka")
                        .HasForeignKey("Domain.Statystyka", "ZawodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("Domain.Zawodnik", b =>
                {
                    b.HasOne("Domain.Klub", "Klub")
                        .WithMany("Zawodnicy")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Domain.Klub", b =>
                {
                    b.Navigation("Zawodnicy");
                });

            modelBuilder.Entity("Domain.Zawodnik", b =>
                {
                    b.Navigation("Statystyka");
                });
#pragma warning restore 612, 618
        }
    }
}
